module.exports = {
    // 1. Top Gaming/Streaming Markets
    USA: { name: 'USA', keywords: ['usa', 'us', 'united states', 'america'] },
    CHN: { name: 'China', keywords: ['chn', 'cn', 'china', 'prc'] },
    JPN: { name: 'Japan', keywords: ['jpn', 'jp', 'japan', 'nihon'] },
    KOR: { name: 'South Korea', keywords: ['kor', 'kr', 'korea', 'south korea', 'sk'] },
    BRA: { name: 'Brazil', keywords: ['bra', 'br', 'brazil', 'brasil'] },
    GER: { name: 'Germany', keywords: ['ger', 'de', 'germany', 'deutschland'] },
    GBR: { name: 'UK', keywords: ['gbr', 'gb', 'uk', 'united kingdom', 'britain', 'england'] },
    FRA: { name: 'France', keywords: ['fra', 'fr', 'france'] },
    RUS: { name: 'Russia', keywords: ['rus', 'ru', 'russia'] },
    IND: { name: 'India', keywords: ['ind', 'in', 'india', 'hindustan'] },

    // 2. High Engagement / Esports
    CAN: { name: 'Canada', keywords: ['can', 'ca', 'canada'] },
    ESP: { name: 'Spain', keywords: ['esp', 'es', 'spain', 'espana'] },
    ITA: { name: 'Italy', keywords: ['ita', 'it', 'italy', 'italia'] },
    AUS: { name: 'Australia', keywords: ['aus', 'au', 'australia', 'oz'] },
    MEX: { name: 'Mexico', keywords: ['mex', 'mx', 'mexico'] },
    ARG: { name: 'Argentina', keywords: ['arg', 'ar', 'argentina'] },
    TUR: { name: 'Turkey', keywords: ['tur', 'tr', 'turkey', 'turkiye'] },
    POL: { name: 'Poland', keywords: ['pol', 'pl', 'poland'] },
    SWE: { name: 'Sweden', keywords: ['swe', 'se', 'sweden'] },
    NED: { name: 'Netherlands', keywords: ['ned', 'nl', 'netherlands', 'holland'] },

    // 3. SEA & Growth
    IDN: { name: 'Indonesia', keywords: ['idn', 'id', 'indonesia', 'indo'] },
    PHL: { name: 'Philippines', keywords: ['phl', 'ph', 'philippines', 'pinoy'] },
    THA: { name: 'Thailand', keywords: ['tha', 'th', 'thailand', 'thai'] },
    VNM: { name: 'Vietnam', keywords: ['vnm', 'vn', 'vietnam', 'viet'] },
    MYS: { name: 'Malaysia', keywords: ['mys', 'my', 'malaysia'] },
    SGP: { name: 'Singapore', keywords: ['sgp', 'sg', 'singapore'] },

    // 4. Other Major
    SAU: { name: 'Saudi Arabia', keywords: ['sau', 'sa', 'saudi', 'ksa'] },
    EGY: { name: 'Egypt', keywords: ['egy', 'eg', 'egypt'] },
    ZAF: { name: 'South Africa', keywords: ['zaf', 'za', 'south africa', 'rsa'] },
    UKR: { name: 'Ukraine', keywords: ['ukr', 'ua', 'ukraine'] },
    DNK: { name: 'Denmark', keywords: ['dnk', 'dk', 'denmark'] },
    FIN: { name: 'Finland', keywords: ['fin', 'fi', 'finland'] },
    NOR: { name: 'Norway', keywords: ['nor', 'no', 'norway'] },
    PRT: { name: 'Portugal', keywords: ['prt', 'pt', 'portugal'] },
    TWN: { name: 'Taiwan', keywords: ['twn', 'tw', 'taiwan'] },
    HKG: { name: 'Hong Kong', keywords: ['hkg', 'hk', 'hong kong'] },
    NZL: { name: 'New Zealand', keywords: ['nzl', 'nz', 'new zealand', 'kiwi'] },
    CHE: { name: 'Switzerland', keywords: ['che', 'ch', 'switzerland', 'swiss'] },
    BEL: { name: 'Belgium', keywords: ['bel', 'be', 'belgium'] },
    AUT: { name: 'Austria', keywords: ['aut', 'at', 'austria'] },
    GRC: { name: 'Greece', keywords: ['grc', 'gr', 'greece'] },
    CZE: { name: 'Czechia', keywords: ['cze', 'cz', 'czech', 'czechia'] },
    HUN: { name: 'Hungary', keywords: ['hun', 'hu', 'hungary'] },
    ROU: { name: 'Romania', keywords: ['rou', 'ro', 'romania'] },
    IRL: { name: 'Ireland', keywords: ['irl', 'ie', 'ireland'] },
    PAK: { name: 'Pakistan', keywords: ['pak', 'pk', 'pakistan'] },
    BGD: { name: 'Bangladesh', keywords: ['bgd', 'bd', 'bangladesh'] },
    NGA: { name: 'Nigeria', keywords: ['nga', 'ng', 'nigeria'] },
    COL: { name: 'Colombia', keywords: ['col', 'co', 'colombia'] },
    CHL: { name: 'Chile', keywords: ['chl', 'cl', 'chile'] },
    PER: { name: 'Peru', keywords: ['per', 'pe', 'peru'] },
    VEN: { name: 'Venezuela', keywords: ['ven', 've', 'venezuela'] },
    ARE: { name: 'UAE', keywords: ['are', 'ae', 'uae', 'dubai'] },
    ISR: { name: 'Israel', keywords: ['isr', 'il', 'israel'] }
};
