export const COUNTRIES = {
    // 1. Top Gaming/Streaming Markets
    USA: { name: 'USA', color: '#B22234', flag: 'https://flagcdn.com/w320/us.png' },
    CHN: { name: 'China', color: '#DE2910', flag: 'https://flagcdn.com/w320/cn.png' },
    JPN: { name: 'Japan', color: '#BC002D', flag: 'https://flagcdn.com/w320/jp.png' },
    KOR: { name: 'South Korea', color: '#0047A0', flag: 'https://flagcdn.com/w320/kr.png' },
    BRA: { name: 'Brazil', color: '#009739', flag: 'https://flagcdn.com/w320/br.png' },
    GER: { name: 'Germany', color: '#000000', flag: 'https://flagcdn.com/w320/de.png' },
    GBR: { name: 'UK', color: '#012169', flag: 'https://flagcdn.com/w320/gb.png' },
    FRA: { name: 'France', color: '#0055A4', flag: 'https://flagcdn.com/w320/fr.png' },
    RUS: { name: 'Russia', color: '#D52B1E', flag: 'https://flagcdn.com/w320/ru.png' },
    IND: { name: 'India', color: '#FF9933', flag: 'https://flagcdn.com/w320/in.png' },

    // 2. High Engagement / Esports
    CAN: { name: 'Canada', color: '#C52032', flag: 'https://flagcdn.com/w320/ca.png' },
    ESP: { name: 'Spain', color: '#AA151B', flag: 'https://flagcdn.com/w320/es.png' },
    ITA: { name: 'Italy', color: '#009246', flag: 'https://flagcdn.com/w320/it.png' },
    AUS: { name: 'Australia', color: '#012169', flag: 'https://flagcdn.com/w320/au.png' },
    MEX: { name: 'Mexico', color: '#006847', flag: 'https://flagcdn.com/w320/mx.png' },
    ARG: { name: 'Argentina', color: '#74ACDF', flag: 'https://flagcdn.com/w320/ar.png' },
    TUR: { name: 'Turkey', color: '#E30A17', flag: 'https://flagcdn.com/w320/tr.png' },
    POL: { name: 'Poland', color: '#DC143C', flag: 'https://flagcdn.com/w320/pl.png' },
    SWE: { name: 'Sweden', color: '#FECC00', flag: 'https://flagcdn.com/w320/se.png' },
    NED: { name: 'Netherlands', color: '#AE1C28', flag: 'https://flagcdn.com/w320/nl.png' },

    // 3. SEA & Growth
    IDN: { name: 'Indonesia', color: '#FF0000', flag: 'https://flagcdn.com/w320/id.png' },
    PHL: { name: 'Philippines', color: '#0038A8', flag: 'https://flagcdn.com/w320/ph.png' },
    THA: { name: 'Thailand', color: '#A51931', flag: 'https://flagcdn.com/w320/th.png' },
    VNM: { name: 'Vietnam', color: '#DA251D', flag: 'https://flagcdn.com/w320/vn.png' },
    MYS: { name: 'Malaysia', color: '#010066', flag: 'https://flagcdn.com/w320/my.png' },
    SGP: { name: 'Singapore', color: '#EC1C24', flag: 'https://flagcdn.com/w320/sg.png' },

    // 4. Other Major
    SAU: { name: 'Saudi Arabia', color: '#165D31', flag: 'https://flagcdn.com/w320/sa.png' },
    EGY: { name: 'Egypt', color: '#C09300', flag: 'https://flagcdn.com/w320/eg.png' },
    ZAF: { name: 'South Africa', color: '#007749', flag: "https://flagcdn.com/w320/za.png" },
    UKR: { name: 'Ukraine', color: '#0057B8', flag: 'https://flagcdn.com/w320/ua.png' },
    DNK: { name: 'Denmark', color: '#C60C30', flag: 'https://flagcdn.com/w320/dk.png' },
    FIN: { name: 'Finland', color: '#003580', flag: 'https://flagcdn.com/w320/fi.png' },
    NOR: { name: 'Norway', color: '#BA0C2F', flag: 'https://flagcdn.com/w320/no.png' },
    PRT: { name: 'Portugal', color: '#FF0000', flag: 'https://flagcdn.com/w320/pt.png' },
    TWN: { name: 'Taiwan', color: '#FE0000', flag: "https://flagcdn.com/w320/tw.png" },
    HKG: { name: 'Hong Kong', color: '#DE2910', flag: "https://flagcdn.com/w320/hk.png" },
    NZL: { name: 'New Zealand', color: '#00247D', flag: "https://flagcdn.com/w320/nz.png" },
    CHE: { name: 'Switzerland', color: '#D52B1E', flag: "https://flagcdn.com/w320/ch.png" },
    BEL: { name: 'Belgium', color: '#000000', flag: "https://flagcdn.com/w320/be.png" },
    AUT: { name: 'Austria', color: '#ED2939', flag: "https://flagcdn.com/w320/at.png" },
    GRC: { name: 'Greece', color: '#0D5EAF', flag: "https://flagcdn.com/w320/gr.png" },
    CZE: { name: 'Czechia', color: '#D7141A', flag: "https://flagcdn.com/w320/cz.png" },
    HUN: { name: 'Hungary', color: '#436F4D', flag: "https://flagcdn.com/w320/hu.png" },
    ROU: { name: 'Romania', color: '#002B7F', flag: "https://flagcdn.com/w320/ro.png" },
    IRL: { name: 'Ireland', color: '#169B62', flag: "https://flagcdn.com/w320/ie.png" },
    PAK: { name: 'Pakistan', color: '#00401A', flag: "https://flagcdn.com/w320/pk.png" },
    BGD: { name: 'Bangladesh', color: '#006A4E', flag: "https://flagcdn.com/w320/bd.png" },
    NGA: { name: 'Nigeria', color: '#008751', flag: "https://flagcdn.com/w320/ng.png" },
    COL: { name: 'Colombia', color: '#FCD116', flag: "https://flagcdn.com/w320/co.png" },
    CHL: { name: 'Chile', color: '#D52B1E', flag: "https://flagcdn.com/w320/cl.png" },
    PER: { name: 'Peru', color: '#D91023', flag: "https://flagcdn.com/w320/pe.png" },
    VEN: { name: 'Venezuela', color: '#FCD116', flag: "https://flagcdn.com/w320/ve.png" },
    ARE: { name: 'UAE', color: '#00732F', flag: "https://flagcdn.com/w320/ae.png" },
    ISR: { name: 'Israel', color: '#0038B8', flag: "https://flagcdn.com/w320/il.png" }
};
